
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

panel_iframe:
  vscode:
    title: "VisualCode"
    url: "https://vscode.lan"
    icon: "mdi:microsoft-visual-studio-code"
    require_admin: true
  portainer:
    title: "Portainer"
    url: "https://portainer.lan"
    icon: "mdi:docker"
    require_admin: true
  

python_script:

logger:
  default: info

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.50.5
    - 172.18.0.0/24
    - 172.19.0.0/24
    - 172.20.0.0/24

mqtt:
  broker: 192.168.50.5
  discovery: true

# Text to speech
tts:
  - platform: google_translate
    base_url: "http://192.168.50.5:8123"
 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
frontend:
  themes: !include_dir_merge_named themes

#camera:
  #- platform: mjpeg
  #  name: OctoPrint
  #  still_image_url: http://192.168.50.55/webcam/?action=snapshot
  #  mjpeg_url: http://192.168.50.55/webcam/?action=stream
  #- platform: generic
  #  still_image_url: http://192.168.50.80:2323?cmd=getCamshot&password=fire
  #  name: Fire Tablet
  #- platform: generic
  #  still_image_url: http://192.168.50.81:2323?cmd=getCamshot&password=fire
  #  name: Galaxy Tab A7

wake_on_lan:

switch:
  - platform: wake_on_lan
    name: RAW S1
    host: raw.lan
    mac: "2C:F0:5D:95:DD:14"
    turn_off:
      service: script.raw_hibernate
  - platform: command_line
    switches:
      ps5:
        friendly_name: Playstation 5
        unique_id: ps_5_switch
        command_state: python3 /config/sensors/ps5.py -b -q 192.168.50.169 | grep -q ON
        command_on: python3 /config/sensors/ps5.py -u 1012966755 -w 192.168.50.169 # TODO credential in secret?
        icon_template: "mdi:sony-playstation"

vacuum:
  - platform: xiaomi_vacuum
    host: 192.168.50.35
    token: !secret xiaomi_token
    name: Dreame D9
    
calendar:
  - platform: todoist
    token: !secret todoist_api_key 

media_player:
  - platform: onkyo
    host: 192.168.50.18
    name: Pioneer Receiver
    sources:
      strm-box: Shield
      tv: Beamer
      dvd: Ultra
      video2: PS5
      game: Xbox

sensor:
  - platform: mqtt_room
    device_id: "apple:1006:10-8"
    #device_id: "apple:iphone13-2"
    name: 'Daniels iPhone'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "known:90f15707f857"
    name: 'Daniels Venu 2'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "known:a038f8e05cb6"
    name: 'Daniels Oura'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "apple:1005:9-6"
    #device_id: "apple:ipad8-11"
    name: 'Daniels iPad'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "apple:1005:16-12"
    #device_id: "apple:macbookpro16-2"
    name: 'Daniels MacBook'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  # Tiles
  - platform: mqtt_room
    device_id: "tile:d3f2a809e483"
    name: 'Black Tile'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120  
  - platform: mqtt_room
    device_id: "tile:d8a5b883bfb5"
    name: 'White Tile'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120  
  # D9
  - platform: history_stats
    name: vacuum cleaning since last emptied
    entity_id: vacuum.dreame_d9
    state: "cleaning"
    type: count
    start: "{{ state_attr('input_datetime.d9_last_emptied', 'timestamp') }}"
    end: "{{ now() }}"
  # PS5
  - platform: command_line
    name: ps5 ext
    unique_id: ps5_ext
    command: python3 /config/sensors/ps5.py -q 192.168.50.169
    scan_interval: 10
  # System monitor
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: load_1m       
      - type: load_5m       
      - type: load_15m  
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot

binary_sensor:
  # https://github.com/wicol/ha-config/blob/master/binary_sensors.yaml#L21
  - platform: command_line
    name: ps5
    unique_id: ps5
    command: python3 /config/sensors/ps5.py -b -q 192.168.50.169
    scan_interval: 10

input_boolean:
  shelly_bad_manual:
    name: Bad Rollo Manuell
  buro_rollo_balkon_manual:
    name: Büro Rollo Balkon Manuell
  buro_rollo_manual:
    name: Büro Rollo Manuell
  kuche_rollo_links_manual:
    name: Küche Rollo links Manuell
  kuche_rollo_rechts_manual:
    name: Küche Rollo rechts Manuell
  schlafzimmer_rollo_balkon_manual:
    name: Schlafzimmer Rollo Balkon Manuell
  schlafzimmer_rollo_links_manual:
    name: Schlafzimmer Rollo links Manuell
  schlafzimmer_rollo_rechts_manual:
    name: Schlafzimmer Rollo rechts Manuell
  wohnzimmer_rollo_manual:
    name: Wohnzimmer Rollo Manuell
  wohnzimmer_rollo_balkon_links_manual:
    name: Wohnzimmer Rollo Balkon links Manuell
  wohnzimmer_rollo_balkon_rechts_manual:
    name: Wohnzimmer Rollo Balkon rechts Manuell

timer:
  shelly_bad_manual:
    name: Bad Rollo Manuell
    restore: true
  buro_rollo_balkon_manual:
    name: Büro Rollo Balkon Manuell
    restore: true
  buro_rollo_manual:
    name: Büro Rollo Manuell
    restore: true
  kuche_rollo_links_manual:
    name: Küche Rollo links Manuell
    restore: true
  kuche_rollo_rechts_manual:
    name: Küche Rollo rechts Manuell
    restore: true
  schlafzimmer_rollo_balkon_manual:
    name: Schlafzimmer Rollo Balkon Manuell
    restore: true
  schlafzimmer_rollo_links_manual:
    name: Schlafzimmer Rollo links Manuell
    restore: true
  schlafzimmer_rollo_rechts_manual:
    name: Schlafzimmer Rollo rechts Manuell
    restore: true
  wohnzimmer_rollo_manual:
    name: Wohnzimmer Rollo Manuell
    restore: true
  wohnzimmer_rollo_balkon_links_manual:
    name: Wohnzimmer Rollo Balkon links Manuell
    restore: true
  wohnzimmer_rollo_balkon_rechts_manual:
    name: Wohnzimmer Rollo Balkon rechts Manuell
    restore: true


browser_mod:
  prefix: "browser_"
  devices:
    36325f2a-8626fd56:
      name: dashboard
      camera: false
      disable:
        - media_player
        - light
    fc203975-d058255d:
      name: galaxy
      camera: false
      disable:
        - media_player
        - light
  disable:
    - all

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.50.0/24
  customize:
    device_tracker.daniel_ble:
      icon: mdi:bluetooth
    sensor.daniel_ble:
      icon: mdi:bluetooth
    sensor.daniels_oura:
      icon: mdi:ring
    sensor.daniels_venu_2:
      icon: mdi:watch
    sensor.daniels_iphone:
      icon: mdi:cellphone
    sensor.daniels_ipad:
      icon: mdi:tablet
    sensor.daniels_macbook:
      icon: mdi:laptop

zha:
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      ikea_provider: true
      ledvance_provider: true