
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

panel_iframe:
  vscode:
    title: "VisualCode"
    url: "http://192.168.50.5:8443"
    icon: "mdi:microsoft-visual-studio-code"
    require_admin: true
  portainer:
    title: "Portainer"
    url: "http://portainer.lan"
    icon: "mdi:docker"
    require_admin: true
  

python_script:

logger:
  default: info

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.50.87
    - 172.19.0.0/24

mqtt:
  broker: 192.168.50.5
  discovery: true

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
frontend:
  themes: !include_dir_merge_named themes


camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.50.55/webcam/?action=snapshot
    mjpeg_url: http://192.168.50.55/webcam/?action=stream

stream:

wake_on_lan:

switch:
  - platform: wake_on_lan
    name: RAW S1
    host: raw.lan
    mac: "2C:F0:5D:95:DD:14"
    turn_off:
      service: script.raw_hibernate
  - platform: command_line
    switches:
      ps5:
        friendly_name: Playstation 5
        unique_id: ps_5_switch
        command_state: python3 /config/sensors/ps5.py -b -q 192.168.50.169 | grep -q ON
        command_on: python3 /config/sensors/ps5.py -u 1012966755 -w 192.168.50.169 # TODO credential in secret?
        icon_template: "mdi:sony-playstation"

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

vacuum:
  - platform: xiaomi_vacuum
    host: 192.168.50.35
    token: !secret xiaomi_token
    name: Dreame D9
    

calendar:
  - platform: todoist
    token: !secret todoist_api_key 

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

media_player:
  - platform: onkyo
    host: 192.168.50.18
    name: Pioneer Receiver
    sources:
      strm-box: Shield
      tv: Beamer
      dvd: Ultra
      video2: PS5
      game: Xbox

sensor:
  - platform: mqtt_room
    device_id: "apple:iphone13-2"
    name: 'Daniels iPhone'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "name:venu-2"
    name: 'Daniels Venu 2'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "name:oura_a038f8e05cb6"
    name: 'Daniels Oura'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "apple:ipad8-11"
    name: 'Daniels iPad'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    device_id: "apple:macbookpro16-2"
    name: 'Daniels MacBook'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120
  # D9
  - platform: history_stats
    name: vacuum cleaning since last emptied
    entity_id: vacuum.dreame_d9
    state: "cleaning"
    type: count
    start: "{{ states.input_boolean.vacuum_emptied.last_changed }}"
    end: "{{ now() }}"
  # PS5
  - platform: command_line
    name: ps5 ext
    command: python3 /config/sensors/ps5.py -q 192.168.50.169
    scan_interval: 10
  # Aftership
  - platform: aftership
    api_key: "074798d7-1644-426d-a6eb-613e15d5f8ae"

binary_sensor:
  # https://github.com/wicol/ha-config/blob/master/binary_sensors.yaml#L21
  - platform: command_line
    name: ps5
    command: python3 /config/sensors/ps5.py -b -q 192.168.50.169
    scan_interval: 10


homeassistant:
  customize:
    device_tracker.daniel_ble:
      icon: mdi:bluetooth
    sensor.daniel_ble:
      icon: mdi:bluetooth
    sensor.daniels_oura:
      icon: mdi:ring
    sensor.daniels_venu_2:
      icon: mdi:watch
    sensor.daniels_iphone:
      icon: mdi:cellphone
    sensor.daniels_ipad:
      icon: mdi:tablet
    sensor.daniels_macbook:
      icon: mdi:laptop

zha:
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      ikea_provider: true
      ledvance_provider: true
