vacuum_clean_zone:
  description: Start the cleaning operation in the selected area.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    zone:
      description: Coordinates.
      example: "819,-263,4424,2105"
      required: true
      selector:
        text:
    repeats:
      description: Number of cleaning passes for each zone between 1 and 10.
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 10

vacuum_set_restricted_zone:
  description: Define virtual walls, restricted zones, and/or no mop zones.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    walls:
      description: Virtual walls.
      example: "[819,-263,4424,2105],[-2001,-3050,-542,515]"
      required: false
      selector:
        text:
    zones:
      description: No go zones.
      example: "[819,-263,4424,2105],[-2001,-3050,-542,515]"
      required: false
      selector:
        text:
    mops:
      description: No mop zones.
      example: "[819,-263,4424,2105],[-2001,-3050,-542,515]"
      required: false
      selector:
        text:

vacuum_remote_control_move_step:
  description: Remotely control move the bot one step.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    rotation:
      description: Turn in binary degrees between -128 and 128.
      example: 64
      required: true
      selector:
        number:
          min: -128
          max: 128
          mode: box
    velocity:
      description: Move speed, from 100 (forward) to -300 (backward)
      example: 100
      required: true
      selector:
        number:
          min: -300
          max: 100
          mode: box
vacuum_set_water_level:
  description: Set water level for mopping.
  target:
    entity:
      domain: vacuum
  fields:
    water_level:
      description: water level, 1:low, 2:medium, 3:high. Numbers are also accepted.
      default: "medium"
      required: true
      selector:
        select:
          options:
            - "low"
            - "medium"
            - "high"

vacuum_install_voice_pack:
  description: Install official or custom voice pack.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    lang_id:
      description: "Language ID of this pack"
      example: "DE"
      required: true
      selector:
        text:
    url:
      description: "Url of this pack it should be reachable by the vacuum bot"
      example: "http://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/package/deyu.tar.gz"
      required: true
      selector:
        text:
    md5:
      description: "MD5 checksum of the language pack"
      example: "d25986c1f608c0897475707e77d856f9"
      required: true
      selector:
        text:
    size:
      description: "Size of the language pack in bytes"
      example: 4067845
      required: true
      selector:
        number:
          mode: box

vacuum_set_clean_cloth_tip:
  description: Set delay of clean cloth reminder.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    delay:
      description: "Delay in minutes. (0 = disable)"
      example: 45
      required: true
      selector:
        number:
          min: 0
          max: 120
          mode: box

vacuum_clean_room_by_id:
  description: Start the cleaning operation in the selected rooms.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    rooms:
      description: List of rooms to be cleaned. Only room's Character or an array of room's character, repeats, fan speed and mop mode to override the default values per room.
      example: A
      required: true
      selector:
        object:
    repeats:
      description: Number of cleaning passes for every selected room (unless it is overridden by rooms parameter).
      example: 2
      required: true
      selector:
        number:
          min: 1
          max: 10
    clean_mode:
      description: Fan speed for every selected room (unless it is overridden by rooms parameter).
      example: 1
      required: true
      selector:
        number:
          min: 0
          max: 4
          mode: box
    mop_mode:
      description: Water level for every selected room (unless it is overridden by rooms parameter).
      example: 3
      required: true
      selector:
        number:
          min: 1
          max: 3
          mode: box

vacuum_reset_filter_life:
  description: Reset filter life to 100%.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"

vacuum_reset_main_brush_life:
  description: Reset main brush life to 100%.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"

vacuum_reset_side_brush_life:
  description: Reset side brush life to 100%.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"

vacuum_select_map:
  description: Select current map. Used when havving multiple maps/floors.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    map_id:
      description: id of the map to be selected.
      example: 14
      required: true
      selector:
        number:
          mode: box

vacuum_set_audio_volume:
  description: Set voice feedback's audio volume.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    volume:
      description: Volume level.
      example: 80
      required: true
      selector:
        number:
          min: 0
          max: 100

vacuum_do_not_disturb:
  description: Enable/disable DnD functionallity and/or setting its start and end time.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    dnd_enabled:
      description: "Enable or disable DnD feature"
      example: "true"
      required: false
      selector:
        boolean:
    dnd_start:
      description: "Start time of DnD feature."
      example: "22:00"
      required: false
      selector:
        text:
    dnd_stop:
      description: "Start time of DnD feature."
      example: "6:30"
      required: false
      selector:
        text:

vacuum_set_carpet_boost:
  description: Enable/disable carpet boost functionallity.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    carpet_boost_enabled:
      description: "Enable or disable carpet boost feature"
      example: "false"
      required: true
      selector:
        boolean:

vacuum_set_multi_map:
  description: Enable/disable multi map functionallity.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    multi_map_enabled:
      description: "Enable or disable multi map feature"
      example: "false"
      required: true
      selector:
        boolean:

vacuum_rename_map:
  description: Rename a map.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    map_id:
      description: "ID of the map"
      example: "14"
      required: true
      selector:
        text:
    map_name:
      description: "New name of the map"
      example: "Ground Floor"
      required: true
      selector:
        text:
